### ISSUE TITLE
Contact section?

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/docs#2]
Should we incorporate a contact session, in case someone has questions or want to reach out?
I was thinking just some bullets with Bertrand's email and maybe his tw handle?
Maybe also a link to this issues section? 

Maybe it's too short for a whole section but it will help with visibility.

**Comment by alexisthual** [comment]
Very nice! 🎉 

I have minor comments:
- maybe rename the "Contact" section to "Miscellaneous"? This way we can add other subsections like License, etc later on. "Contact Us" would still be a sub-section
- maybe change `bertrand.thirion@inria.fr` to `firstname.lastname@inria.fr` to prevent some bots / really bad language models from sending spam to Bertrand 😅

**Comment by ferponcem** [comment]
@alexisthual Do you mean putting literally `firstname.lastname@inria.fr` so that people fill it up? Just to make sure :joy:

**Comment by alexisthual** [comment]
Yes that's what I meant :)

**Comment by ferponcem** [comment]
Awesome, thanks all for your comments!
I'll close this for now, I'm sure the `Miscellaneous` section will keep on growing (:
